project_id = "upwzxjjeiuphlqsyztvm"

[functions.payments-webhook]
verify_jwt = false

[functions.create-checkout]
verify_jwt = false

[functions.get-stripe-price]
verify_jwt = false

[functions.auto-approve-jobs]
verify_jwt = false

[functions.create-job-checkout]
verify_jwt = false